import { FC } from "react";
import Head from "next/head";

interface PageHeadProps {
  links: string[];
}

const PageHead: FC<PageHeadProps> = (props) => {
  return (
    <Head>
      <title>USVI Sports Commission</title>
      <meta name="description" content="Generated by tony" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default PageHead;
